[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo", "php83Extensions.pdo_mysql", "php83-fpm", "caddy"]

[start]
cmd = "php-fpm83 -F -d listen=127.0.0.1:9000 & caddy run --config /app/Caddyfile --adapter caddyfile"
```

**`Caddyfile`**
```
:{$PORT}

root * /app
encode gzip

php_fastcgi 127.0.0.1:9000
file_server
